# Testes da rotina que gera os vetores de entrada com base em uma série temporal

## 1. Importando as bibliotecas necessárias

In [1]:
import numpy as np

## 2. Definindo a função

In [2]:
def criar_vetores_treino_teste(dados, K, L, n):
    """
    Descrição:
    ----------
        Função para criar os vetores de entrada e saída para as etapas de treinamento e teste para uma série temporal.
    
    Parâmetros:
    -----------
    dados: np.array
        Conjunto de dados que você quer utilizar para criar os vetores
    K: int
        O número de entradas utilizado para a predição
    L: int
        O passo de predição 
    n: int
        A posicao a partir da qual se deseja prever algum valor
    """
    
    # checa se a partir da posição atual podemos criar um vetor de amostras dado um K
    if (n < (K-1)):
        raise ValueError("n + 1 deve ser maior ou igual a (K-1)!")
        
    if ((n+L) > (len(dados)-1)):
        raise ValueError("O passo de predição para o instante atual (n = ", n,") não deve estourar o número de dados na série temporal!")
    
    vetor_entrada = np.array(dados[(n-(K-1)):(n+1)])
    vetor_entrada = np.insert(vetor_entrada, 0, 1) # insere o elemento x^0 no vetor
    vetor_saida = np.array(dados[n+L])
    
    return vetor_entrada, vetor_saida

In [3]:
def criar_matrizes_treino_teste(serie_temporal, K, L):
    """
    Descrição:
    ----------
        Função para criar as matrizes com os vetores de entrada e saída para as etapas de treinamento e teste.
    
    Parâmetros:
    -----------
    serie_temporal: np.array
        Série temporal que será utilizada para criar os vetores
    K: int
        O número de entradas utilizado para a predição
    L: int
        O passo de predição 
    """
    
    if (K <= 0):
        raise ValueError("O hiperparâmetro K deve ser um inteiro positivo!")
    
    num_dados = len(serie_temporal)
    
    matriz_entrada = np.array([])
    matriz_saida = np.array([])
    
    for n in range((K-1), (num_dados-L)):
        vetor_entrada, vetor_saida = criar_vetores_treino_teste(serie_temporal, K, L, n)
        
        if(len(matriz_entrada) == 0):
            matriz_entrada = vetor_entrada
        else:
            matriz_entrada = np.vstack((matriz_entrada, vetor_entrada))
                
        if(len(matriz_saida) == 0):
            matriz_saida = np.array([vetor_saida])
        else:
            matriz_saida = np.vstack((matriz_saida, vetor_saida))
        
    return matriz_entrada, matriz_saida

## 3. Testando

In [4]:
serie_temporal = np.array(range(0, 101))

In [5]:
K = 2
L = 1

In [6]:
matriz_entrada, matriz_saida = criar_matrizes_treino_teste(serie_temporal, K, L)

In [7]:
print(matriz_entrada)

[[ 1  0  1]
 [ 1  1  2]
 [ 1  2  3]
 [ 1  3  4]
 [ 1  4  5]
 [ 1  5  6]
 [ 1  6  7]
 [ 1  7  8]
 [ 1  8  9]
 [ 1  9 10]
 [ 1 10 11]
 [ 1 11 12]
 [ 1 12 13]
 [ 1 13 14]
 [ 1 14 15]
 [ 1 15 16]
 [ 1 16 17]
 [ 1 17 18]
 [ 1 18 19]
 [ 1 19 20]
 [ 1 20 21]
 [ 1 21 22]
 [ 1 22 23]
 [ 1 23 24]
 [ 1 24 25]
 [ 1 25 26]
 [ 1 26 27]
 [ 1 27 28]
 [ 1 28 29]
 [ 1 29 30]
 [ 1 30 31]
 [ 1 31 32]
 [ 1 32 33]
 [ 1 33 34]
 [ 1 34 35]
 [ 1 35 36]
 [ 1 36 37]
 [ 1 37 38]
 [ 1 38 39]
 [ 1 39 40]
 [ 1 40 41]
 [ 1 41 42]
 [ 1 42 43]
 [ 1 43 44]
 [ 1 44 45]
 [ 1 45 46]
 [ 1 46 47]
 [ 1 47 48]
 [ 1 48 49]
 [ 1 49 50]
 [ 1 50 51]
 [ 1 51 52]
 [ 1 52 53]
 [ 1 53 54]
 [ 1 54 55]
 [ 1 55 56]
 [ 1 56 57]
 [ 1 57 58]
 [ 1 58 59]
 [ 1 59 60]
 [ 1 60 61]
 [ 1 61 62]
 [ 1 62 63]
 [ 1 63 64]
 [ 1 64 65]
 [ 1 65 66]
 [ 1 66 67]
 [ 1 67 68]
 [ 1 68 69]
 [ 1 69 70]
 [ 1 70 71]
 [ 1 71 72]
 [ 1 72 73]
 [ 1 73 74]
 [ 1 74 75]
 [ 1 75 76]
 [ 1 76 77]
 [ 1 77 78]
 [ 1 78 79]
 [ 1 79 80]
 [ 1 80 81]
 [ 1 81 82]
 [ 1 82 83]
 [ 1

In [8]:
print(matriz_saida)

[[  2]
 [  3]
 [  4]
 [  5]
 [  6]
 [  7]
 [  8]
 [  9]
 [ 10]
 [ 11]
 [ 12]
 [ 13]
 [ 14]
 [ 15]
 [ 16]
 [ 17]
 [ 18]
 [ 19]
 [ 20]
 [ 21]
 [ 22]
 [ 23]
 [ 24]
 [ 25]
 [ 26]
 [ 27]
 [ 28]
 [ 29]
 [ 30]
 [ 31]
 [ 32]
 [ 33]
 [ 34]
 [ 35]
 [ 36]
 [ 37]
 [ 38]
 [ 39]
 [ 40]
 [ 41]
 [ 42]
 [ 43]
 [ 44]
 [ 45]
 [ 46]
 [ 47]
 [ 48]
 [ 49]
 [ 50]
 [ 51]
 [ 52]
 [ 53]
 [ 54]
 [ 55]
 [ 56]
 [ 57]
 [ 58]
 [ 59]
 [ 60]
 [ 61]
 [ 62]
 [ 63]
 [ 64]
 [ 65]
 [ 66]
 [ 67]
 [ 68]
 [ 69]
 [ 70]
 [ 71]
 [ 72]
 [ 73]
 [ 74]
 [ 75]
 [ 76]
 [ 77]
 [ 78]
 [ 79]
 [ 80]
 [ 81]
 [ 82]
 [ 83]
 [ 84]
 [ 85]
 [ 86]
 [ 87]
 [ 88]
 [ 89]
 [ 90]
 [ 91]
 [ 92]
 [ 93]
 [ 94]
 [ 95]
 [ 96]
 [ 97]
 [ 98]
 [ 99]
 [100]]
